export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

export const AUTHENTICATE = 'AUTHENTICATE'
export const UNAUTHENTICATE = 'UNAUTHENTICATE'

export const LOAD_FORM='LOAD_FORM'

export const SELECT_CLIENT = 'SELECT_CLIENT'
export const FETCH_CLIENTS = 'FETCH_CLIENTS'
